# Generated by Django 2.2 on 2019-04-08 14:29

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interaction', '0046_populate_dit_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='archived',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='archived_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='archived_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='source',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('complete', 'Complete')], max_length=255, null=True),
        ),
    ]
