# Generated by Django 2.2.7 on 2019-11-18 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_squashed_0010_auto_20180613_1553'),
        ('interaction', '0069_add_composite_index_to_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='country_of_export',
            field=models.ForeignKey(blank=True, help_text='Country that was in export related discussion during the interaction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='metadata.Country'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='export_interest_category',
            field=models.CharField(blank=True, choices=[('not_interested', 'Not interested'), ('currenty_exporting', 'Currently exporting to'), ('future_interest', 'Future country of interest')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='was_a_country_discussed',
            field=models.BooleanField(default=False),
        ),
    ]
