# Generated by Django 2.2 on 2019-04-30 09:47

import datahub.core.validators.field
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion

from pathlib import PurePath

from django.db import migrations, models
from datahub.core.migration_utils import load_yaml_data_in_migration
import uuid

metadata_files = [
    'opportunity_status.yaml',
]


def load_metadata(apps, schema_editor):
    for file_name in metadata_files:
        load_yaml_data_in_migration(
            apps,
            PurePath(__file__).parent / f'0001_initial/{file_name}',
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor_profile', '0003_auto_20190412_1437'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metadata', '0025_update_sector_indexes'),
        ('company', '0068_ch_registered_address_postcode_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeCapitalUKOpportunity',
            fields=[
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('required_checks_conducted_on', models.DateField(blank=True, null=True, validators=[datahub.core.validators.field.validate_date_is_in_the_past])),
                ('opportunity_name', models.CharField(max_length=80)),
                ('opportunity_description', models.TextField(blank=True, default='')),
                ('total_investment_sought', models.BigIntegerField(blank=True, help_text='Total investment sought amount in GBP', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000)])),
                ('investment_secured_so_far', models.BigIntegerField(blank=True, help_text='Investment secured so far amount in GBP', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000)])),
                ('gross_development_value', models.BigIntegerField(blank=True, help_text='GDV amount in GBP', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000)])),
                ('capital_expenditure', models.BigIntegerField(blank=True, help_text='CapEx amount in GBP', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000000)])),
                ('asset_classes_of_interest', models.ManyToManyField(blank=True, related_name='_largecapitalukopportunity_asset_classes_of_interest_+', to='investor_profile.AssetClassInterest')),
                ('construction_risks', models.ManyToManyField(blank=True, related_name='_largecapitalukopportunity_construction_risks_+', to='investor_profile.ConstructionRisk')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dit_contacts', models.ManyToManyField(blank=True, related_name='_largecapitalukopportunity_dit_contacts_+', to=settings.AUTH_USER_MODEL)),
                ('estimated_return_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investor_profile.ReturnRate')),
                ('investment_types', models.ManyToManyField(blank=True, related_name='_largecapitalukopportunity_investment_types_+', to='investor_profile.LargeCapitalInvestmentType')),
                ('lead_dit_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('required_checks_conducted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investor_profile.RequiredChecksConducted')),
                ('required_checks_conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LargeCapitalUKOpportunityAbandonmentReason',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LargeCapitalUKOpportunityFundingSource',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LargeCapitalUKOpportunityStatus',
            fields=[
                ('disabled_on', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('order', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LargeCapitalUKOpportunityStatusDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dit_supported', models.BooleanField(null=True)),
                ('abandonment_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uk_opportunity.LargeCapitalUKOpportunityAbandonmentReason')),
                ('funding_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uk_opportunity.LargeCapitalUKOpportunityFundingSource')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_details_log', to='uk_opportunity.LargeCapitalUKOpportunity')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='uk_opportunity.LargeCapitalUKOpportunityStatus')),
            ],
        ),
        migrations.CreateModel(
            name='LargeCapitalUKOpportunityPromoter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uk_opportunity_promoters', to='company.Company')),
                ('key_client_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uk_opportunity_promoters', to='company.Contact')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoters', to='uk_opportunity.LargeCapitalUKOpportunity')),
            ],
        ),
        migrations.AddField(
            model_name='largecapitalukopportunity',
            name='status_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uk_opportunity.LargeCapitalUKOpportunityStatusDetails'),
        ),
        migrations.AddField(
            model_name='largecapitalukopportunity',
            name='time_scales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='investor_profile.TimeHorizon'),
        ),
        migrations.AddField(
            model_name='largecapitalukopportunity',
            name='uk_region_locations',
            field=models.ManyToManyField(blank=True, related_name='_largecapitalukopportunity_uk_region_locations_+', to='metadata.UKRegion', verbose_name='possible UK regions'),
        ),
        migrations.RunPython(load_metadata, migrations.RunPython.noop),
    ]
