# Generated by Django 2.1.4 on 2019-03-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0057_remove_investmentproject_likelihood_of_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproject',
            name='name_bob',
            field=models.CharField(default='he', max_length=255),
            preserve_default=False,
        ),
    ]
