# Generated by Django 2.1.4 on 2019-03-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0058_investmentproject_name_bob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproject',
            name='name_bob',
        ),
    ]
