# Generated by Django 2.1.3 on 2018-12-04 12:58

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0049_populate_one_list_tier_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='duns_number',
            field=models.CharField(blank=True, default='', help_text='Dun & Bradstreet unique identifier. Nine-digit number with leading zeros.', max_length=9, validators=[django.core.validators.MinLengthValidator(9), django.core.validators.MaxLengthValidator(9), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')]),
            preserve_default=False,
        ),
    ]
